//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTUBAdministrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityAttachment = new HashSet<ActivityAttachment>();
            this.ActivityApplicant = new HashSet<ActivityApplicant>();
            this.ActivityCoOrganizer = new HashSet<ActivityCoOrganizer>();
            this.ActivityOrganizer = new HashSet<ActivityOrganizer>();
            this.ActivityResult = new HashSet<ActivityResult>();
            this.ActivitySponsor = new HashSet<ActivitySponsor>();
        }
    
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public short ActivityType { get; set; }
        public Nullable<int> ApplicantLimit { get; set; }
        public string Meal { get; set; }
        public string StudyProof { get; set; }
        public Nullable<double> StudyHours { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ActivityStartTime { get; set; }
        public Nullable<System.DateTime> ActivityEndTime { get; set; }
        public Nullable<System.DateTime> ApplyStartTime { get; set; }
        public Nullable<System.DateTime> ApplyEndTime { get; set; }
        public string CreateID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyID { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Record { get; set; }
    
        public virtual ActivityType ActivityType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttachment> ActivityAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityApplicant> ActivityApplicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCoOrganizer> ActivityCoOrganizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityOrganizer> ActivityOrganizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityResult> ActivityResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitySponsor> ActivitySponsor { get; set; }
    }
}
