//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTUBAdministrator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityApplicant> ActivityApplicant { get; set; }
        public virtual DbSet<ActivityApplicantInformation> ActivityApplicantInformation { get; set; }
        public virtual DbSet<ActivityAttachment> ActivityAttachment { get; set; }
        public virtual DbSet<ActivityCoOrganizer> ActivityCoOrganizer { get; set; }
        public virtual DbSet<ActivityOrganizer> ActivityOrganizer { get; set; }
        public virtual DbSet<ActivityResult> ActivityResult { get; set; }
        public virtual DbSet<ActivitySponsor> ActivitySponsor { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<CodeTable> CodeTable { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentAuthentication> DepartmentAuthentication { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserAuthentication> UserAuthentication { get; set; }
    }
}
